name: video_notebook
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - tqdm
  - opencv
  - ffmpeg
  - pip
  - pip:
      - ffmpeg-python
      - holoviews
      - panel
      - jupyter_bokeh